name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.6.0'

      - name: Install dependencies
        run: npm install

      - name: Check code formatting with Prettier
        run: npm run format -- --check

      - name: Build project
        run: npm run build
